<?php 

$name = 'Products list';
$this->headTitle($name);
?>
<h1>
	<?php echo $this->escapeHtml($name); ?>
</h1>
<p>
	<a href="<?php echo $this->url('product', array('action'=>'create'));?>">Add
		new product</a>
</p>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Descriprion</th>
		<th>Creation date</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($products as $product) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($product->getName());?></td>
		<td><?php echo $this->escapeHtml($product->getDescription());?></td>
		<td><?php echo $this->escapeHtml($product->getCreationdate());?></td>
		<td><a
			href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $product->getId()));?>">Edit</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>