<?php 

$name = 'Products list';
$this->headTitle($name);
?>
<h1>
	<?php echo $this->escapeHtml($name); ?>
</h1>
<p>
	<a href="<?php echo $this->url('product', array('action'=>'create'));?>">Add
		new product</a>
</p>

<table class="table">
	<tr>
		<th>Image</th>
		<th>Name</th>
		<th>Creation date</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($products as $product) { ?>
	<tr>
		<td>
		<a href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $product->getId()));?>">
		<?php if($product->getImage() == null) {?>
			<img alt="Product image" src="/img/product/thumb/default_product.jpg">
		<?php }else{ ?>
			<img alt="<?php echo $this->escapeHtml($product->getImage());?>" src="/img/product/thumb/<?php echo $this->escapeHtml($product->getImage());?>">
		<?php }?>
		</a>
		</td>
		<td><?php echo $this->escapeHtml($product->getName());?></td>
		<td><?php echo $product->getCreationdate()->format('Y-m-d H:i:s'); ?></td>
		<td><a
			href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $product->getId()));?>">Edit</a>
		</td>
	</tr>
	<?php } ?>
</table>